CREATE TABLE `blogs_vlogs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`type` enum('blog','vlog') NOT NULL DEFAULT 'blog',
	`title` varchar(500) NOT NULL,
	`slug` varchar(500) NOT NULL,
	`excerpt` text,
	`content` text,
	`coverImage` text,
	`youtubeUrl` text,
	`author` varchar(255),
	`tourSlug` varchar(255),
	`tourName` varchar(255),
	`destination` varchar(100),
	`tags` json,
	`published` boolean NOT NULL DEFAULT false,
	`featured` boolean NOT NULL DEFAULT false,
	`publishedAt` timestamp,
	`sortOrder` int NOT NULL DEFAULT 0,
	`metaTitle` varchar(500),
	`metaDescription` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `blogs_vlogs_id` PRIMARY KEY(`id`),
	CONSTRAINT `blogs_vlogs_slug_unique` UNIQUE(`slug`)
);
